### ISSUE TITLE
 MobiSpectral APK: New Preview Available,  File is in Owner's Trash

### ISSUE THREAD

**Issue by szl2** [mobispectral/MobiSpectral-Android#1]
Dear author, 

I am following the instructing to dowonload MobiSpectral APK with the link in read me

> [MobiSpectral APK](https://drive.google.com/file/d/1jYZD7jS99K_1JttCduFtIrcx7TrS7R-X/view?usp=sharing).

But it seems the file is no more there.

Would you mind sharing the file with me?

<img width="1307" alt="Screenshot 2024-01-19 at 14 47 54" src="https://github.com/mobispectral/MobiSpectral-Android/assets/50324441/e06fc915-b1a0-4e69-8aef-07ab9a187368">

Thank you

Zhiying Li

**Comment by mobispectral** [comment]
Hi Li,

We have updated the link.

Regards
Neha
